### ISSUE TITLE
Making transition smooth

### ISSUE THREAD

**Issue by Entrebear** [de-men/orientation_widget#1]
Hi

I am using the package to switch from a portrait widget to a landscape widget and back. The transition rotates and is very 'jerky'. Is the any way to provide for a smoother transition that looks good?

**Comment by thaihuynhxyz** [comment]
Hi @Entrebear, Could you please show your code for the landscape page?

**Comment by Entrebear** [comment]
Hi

Please see the beginning of the code below:

```
class Game extends StatefulWidget {
  const Game({Key? key}) : super(key: key);

  @override
  State<Game> createState() => _GameState();
}

class _GameState extends State<Game> {

  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersive);
    SystemChrome.setSystemUIOverlayStyle(
      const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
      ),
    );
  

    return OrientationWidget.landscape(
      child: SafeArea(
         child: Scaffold(

```
Many Thanks

**Comment by thaihuynhxyz** [comment]
Hi @Entrebear, Could you please try to use OrientationWidget.landscape to wrap your Game widget?

**Comment by Entrebear** [comment]
It looks a little better with that code change, but still not great. Any further suggestions to make the transition smoother?

**Comment by thaihuynhxyz** [comment]
@Entrebear, Could you try importing the library as below?

```yaml
  orientation_widget:
    git:
      url: https://github.com/de-men/orientation_widget.git
      ref: 1-making-transition-smooth
```

**Comment by Entrebear** [comment]
This is what its doing now:

![Screen_recording_20231118_135902](https://github.com/de-men/orientation_widget/assets/104825096/89f5c1f9-c17c-4572-86e5-7b104cd21235)

Note: I had to remove the Orientation.landscape that wrapped the Game() widget as it was giving an error that there were two orientation widgets in the tree.

**Comment by thaihuynhxyz** [comment]
I expect we just need to use the Orientation request once when navigating to a new page. Please use it as the root widget when you navigate.

**Comment by Entrebear** [comment]
This is without using the Orientation request just when navigating:

![Screen_recording_20231122_233404](https://github.com/de-men/orientation_widget/assets/104825096/bdfcee59-e175-478e-8ffc-db99f3107606)

**Comment by thaihuynhxyz** [comment]
Could you please provide more logs or the widget tree by using DevTools? And the code that is used when performing navigation.
![Screenshot 2023-11-24 at 3 37 51 PM](https://github.com/de-men/orientation_widget/assets/29724810/6c41363f-3879-46a5-92ad-87ccc06aa30c)
